Matrices is a very important data structure of the R programming language and like vector, all its values are of the same data types. They are extensively used in machine learning models like linear regression, logistic regression, etc. Linear algebra is the main component of Machine Learning and Deep Learning Algorithms. Matrices are extensively used in optimization and finding the best fit line of regression. In this tutorial, we will cover the following topics:

* Create matrices in R programming language. 

* Update, access and change the dimensions of a matrix.

* Use the cbind(V1, V2) function to bind the V1 and V2 vectors into the column-wise matrix.

* Use the rbind(V1, V2) function to bind the vectors V1 and V2 into the row-wise matrix. 

* Element wise multiplication of two matrices. 

* Matrix multiplication of M1 and M2. 

* Transpose of a matrix.

* Determinant of a matrix,

* Calculate the row sum of a matrix using the rowSums() function.

* Calculate the column sum of a matrix using the colMeans() function. 

* Calculate the row mean of a matrix using the rowMeans() function.

### Creating Matrices in R

Create a matrix using the matrix(V, ncol, nrow, byrow) function that takes three arguments given below:

* The V is a vector of data elements 
* The ncol means the number of columns of the matrix
* the nrow means number of rows of the matrix
* If byrow value is true, then rows will arrange rows wise otherwise column wise

In [1]:
V <- c(1:9)
M <- matrix(V, ncol=3, nrow=3) # default byrow-False
M

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [2]:
M1 <- matrix(V, ncol=3, nrow=3, byrow=TRUE)
M1

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

Now we will create a matrix using cbind() and rbind() functions.

* the cbind(V1, V2) binds the vectors V1 and V2 into the column wise matrix.
* The rbind(V1, V2) binds the vectors V1 and V2 into row-wise matrix.

In [3]:
roll_no <- c(11, 12, 13, 14, 15)
marks <- c(98, 85, 96, 36, 89)

T1 <- cbind(roll_no, marks)
T1

roll_no marks
[1,] 11      98   
[2,] 12      85   
[3,] 13      96   
[4,] 14      36   
[5,] 15      89

In [4]:
T2 <- rbind(roll_no, marks)
T2

[,1] [,2] [,3] [,4] [,5]
roll_no 11   12   13   14   15  
marks   98   85   96   36   89